# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('pic', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
