# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumb', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('url', models.TextField()),
            ],
        ),
    ]
