# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='pic',
            field=models.TextField(blank=True),
        ),
    ]
